version: 2

submodules:
  include: all
  recursive: false

build:
  os: ubuntu-22.04
  tools:
    python: "3.8" # doxysphinx python >= 3.8
  apt_packages:
    - graphviz
  jobs:
    post_install:
      - vcs import doc/source --input https://raw.githubusercontent.com/lbr-stack/lbr_fri_ros2_stack/humble/lbr_fri_ros2_stack/repos.yaml
      - unzip doc/source/fri/FRI-Client-SDK_Cpp.zip -d doc/source/fri/FRI-Client-SDK_Cpp

python:
   install:
   - requirements: requirements.txt
